apiVersion: v1
kind: Secret
metadata:
  name: caretta-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-6.48.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: caretta
    app.kubernetes.io/version: 9.3.1
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  admin-user: YWRtaW4=
  admin-password: Y2FyZXR0YQ==
  ldap-toml: ''
