apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm

resources:
  - open-webui
  - playwright
  - searxng
  - llm-gemma26b
  - llm-gemma12b
  - llm-nemotron
  - llm-qwen36
  - llm-router
