apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zot-pvc-warm
  namespace: dev-infra
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: storage-warm
