apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zot-pvc
  namespace: dev-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
