apiVersion: v1
kind: Service
metadata:
  name: llm-kokoro-service
  namespace: llm
  labels:
    app: llm-kokoro
spec:
  type: NodePort
  selector:
    app: llm-kokoro
  ports:
  - name: http
    port: 8880
    targetPort: 8880
    nodePort: 30880
