apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc-hot
  namespace: llm
  labels:
    app: open-webui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storage-hot
  resources:
    requests:
      storage: 10Gi
