apiVersion: v1
kind: Service
metadata:
  name: llm-flux2-service
  namespace: llm
  labels:
    app: llm-flux2
spec:
  type: NodePort
  selector:
    app: llm-flux2
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30810
