model_list:
  - model_name: google/gemma-4-26B-A4B-it
    litellm_params:
      model: hosted_vllm/google/gemma-4-26B-A4B-it
      api_base: http://llm-gemma26b-service.llm:8000/v1
      api_key: "none"
    model_info:
      supports_reasoning: true
      supports_function_calling: true

  - model_name: black-forest-labs/FLUX.2-klein-9B
    litellm_params:
      model: openai/black-forest-labs/FLUX.2-klein-9B
      api_base: http://llm-flux2-service.llm:8000/v1
      api_key: "dummy"
    model_info:
      mode: image_generation

  - model_name: black-forest-labs/FLUX.2-klein-4B
    litellm_params:
      model: openai/black-forest-labs/FLUX.2-klein-9B
      api_base: http://llm-flux2-service.llm:8000/v1
      api_key: "dummy"
    model_info:
      mode: image_generation

  - model_name: flux-2-klein
    litellm_params:
      model: openai/black-forest-labs/FLUX.2-klein-9B
      api_base: http://llm-flux2-service.llm:8000/v1
      api_key: "dummy"
    model_info:
      mode: image_generation

  - model_name: kokoro
    litellm_params:
      model: openai/kokoro
      api_base: http://llm-kokoro-service.llm:8880/v1
      api_key: "dummy"
    model_info:
      mode: audio_speech

  - model_name: tts-1
    litellm_params:
      model: openai/kokoro
      api_base: http://llm-kokoro-service.llm:8880/v1
      api_key: "dummy"
    model_info:
      mode: audio_speech

  - model_name: whisper-1
    litellm_params:
      model: openai/whisper-1
      api_base: http://llm-whisper-service.llm:8000/v1
      api_key: "dummy"
    model_info:
      mode: audio_transcription

  - model_name: Systran/faster-whisper-small
    litellm_params:
      model: openai/Systran/faster-whisper-small
      api_base: http://llm-whisper-service.llm:8000/v1
      api_key: "dummy"
    model_info:
      mode: audio_transcription



router_settings:
  routing_strategy: usage-based-routing-v2

general_settings:
  alerting: ["email"]
  store_model_in_db: true
  store_prompts_in_spend_logs: true

litellm_settings:
  drop_params: true
  require_auth_for_metrics_endpoint: false
  success_callback: ["prometheus"]
  failure_callback: ["prometheus"]
  callbacks: ["smtp_email"]

