apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: llm-router-config
    files:
      - config.yaml
    options:
      disableNameSuffixHash: true
