apiVersion: v1
kind: Service
metadata:
  name: llm-gemma12b-service
  namespace: llm
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: llm-gemma12b
