apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: buyoutyourcoach
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_DB: buyoutyourcoach
  POSTGRES_USER: buyoutyourcoach
  POSTGRES_PASSWORD: PxnFsPv4lXgpwyTjNPQXZP9r
