apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc-hot
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: storage-hot
