apiVersion: v1
kind: Service
metadata:
  name: laya-service
  namespace: llm
  labels:
    app: laya
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
    name: http
  - port: 8005
    targetPort: 8005
    nodePort: 30805
    name: mcp
  selector:
    app: laya
