apiVersion: v1
kind: Service
metadata:
  name: laya-service
  namespace: llm
  labels:
    app: laya
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
    name: http
  selector:
    app: laya
