apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-controller-gha-rs-controller
  namespace: dev-infra
  labels:
    app.kubernetes.io/name: gha-rs-controller
    app.kubernetes.io/part-of: gha-rs-controller
